Repository so1s/so1s-deploy, pull requests merged in 2022-09, with the labels that each got.

#31 SO1S-252 Deploy Repository public 전환에 따른 ArgoCD Application 수정
  apps/dev/app-backend.yaml
  apps/dev/app-istio.yaml
  apps/dev/app-logging.yaml
  apps/dev/app-monitoring.yaml
  apps/prod/app-backend.yaml
  apps/prod/app-inference.yaml
  apps/prod/app-istio-base.yaml
  apps/prod/app-istio-gateway.yaml
  apps/prod/app-istiod.yaml
  apps/prod/app-logging.yaml
  apps/prod/app-monitoring.yaml
  root-dev.yaml
  root-prod.yaml
Labels: Refactoring

#32 SO1S-363 terraform dev 환경 자동화 istio ingress 오류
  charts/istio/dev-values.yaml
  charts/istio/prod-values.yaml
  charts/istio/templates/ingress.yaml
  charts/istio/values.yaml
Labels: Refactoring

#33 SO1S-280 온프레미스 차트 개발
  .gitignore
  apps/dev/app-database.yaml
  apps/prod/app-sealed-secrets.yaml
  charts/backend/templates/docker-pull-secret.yaml
  charts/backend/templates/gateway.yaml
  charts/backend/templates/sealed-secret.yaml
  charts/backend/templates/swagger/gateway.yaml
  charts/database/.helmignore
  charts/database/Chart.yaml
  charts/database/dev-values.yaml
  charts/database/templates/_helpers.tpl
  charts/database/templates/deployment.yaml
  charts/database/templates/service.yaml
  charts/database/templates/serviceaccount.yaml
  charts/database/templates/storageclass.yaml
  charts/database/templates/tests/test-connection.yaml
  charts/database/values.yaml
  charts/istio/charts/istio-gateway/templates/deployment.yaml
  charts/istio/charts/istio-gateway/values.yaml
  charts/monitoring/charts/grafana/templates/gateway.yaml
  charts/monitoring/templates/prometheus/gateway.yaml
Labels: Structure

#35 SO1S-372 Istio Namespace Injection 코드 추가
  charts/backend/templates/pre-install/clusterrolebinding.yaml
  charts/backend/templates/pre-install/namespace.yaml
  charts/backend/templates/pre-install/serviceaccount.yaml
Labels: Feat, Configuration

#36 Release v0.4.1
  apps/prod/app-backend.yaml
  apps/prod/app-database.yaml
  apps/prod/app-istio-base.yaml
  apps/prod/app-istio-gateway.yaml
  apps/prod/app-istio.yaml
  apps/prod/app-logging.yaml
  apps/prod/app-monitoring.yaml
  charts/argocd/argocd-prod-values.yaml
  charts/backend/dev-values.yaml
  charts/backend/prod-values.yaml
  charts/backend/templates/pre-install/namespace.yaml
  charts/backend/templates/swagger/deployment.yaml
  charts/database/prod-values.yaml
  charts/istio/prod-values.yaml
  root-prod.yaml
  so1s-prod-swagger.service.yaml
  so1s-prod-swagger.virtualservice.yaml
  swagger-ui.deployment.yaml
Labels: Release

#38 SO1S-409 backend 차트 helm pre install job tolerations 설정하기
  apps/dev/app-backend.yaml
  apps/dev/app-monitoring.yaml
  charts/backend/dev-values.yaml
  charts/backend/prod-values.yaml
  charts/backend/templates/pre-install/job.yaml
  charts/backend/values.yaml
  charts/monitoring/dev-values.yaml
  charts/monitoring/prod-values.yaml
  charts/monitoring/templates/pre-install/job.yaml
  charts/monitoring/templates/pre-install/serviceaccount.yaml
  charts/monitoring/values.yaml
  so1s-prod-swagger.service.yaml
  so1s-prod-swagger.virtualservice.yaml
  swagger-ui.deployment.yaml
Labels: Fix, Refactoring

#39 SO1S-408 monitoring namespace label 추가시 job sidecar 생성 이슈
  charts/monitoring/dev-values.yaml
  charts/monitoring/prod-values.yaml
  charts/monitoring/templates/pre-install/clusterrolebinding.yaml
  charts/monitoring/templates/pre-install/job.yaml
  charts/monitoring/templates/pre-install/serviceaccount.yaml
Labels: Feat, Fix
